name: CI

on:
  push:
    branches: [ "feature" ]
  pull_request:
    branches: [ "feature" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
        
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
    

    - name: Gradle Caching
      uses: actions/cache@v3
      with:
        path: |  
            graphy/backend/.gradle/caches
            graphy/backend/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
            ${{ runner.os }}-gradle-
          

    - name: Grant Execute Permission For Gradlew
      run: chmod +x backend/gradlew
      
    
    - name: Build with Gradle
      run: |
        cd backend
        ./gradlew build -x test
    
    - name: Setup MySQL
      uses: samin/mysql-action@v1
      with:
        character set server: utf8
        mysql database: 'graphy'
        mysql user: 'graphy'
        mysql password: ${{ secrets.TEST_MYSQL_PASSWORD }}
        
        
    - name: Make properties
      run: |
        cd backend/src/main/resources
        touch ./application.properties
        echo "${{ secrets.TEST_PROPERTIES }}" > ./application.properties
      shell: bash

    

    - name: Test with Gradle # test application build
      run: |
        cd backend
        ./gradlew test --info
        

    - name: Test Results # test 후 result를 보기 위해 추가
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: ${{ always() }} # test가 실패해도 report를 남기기 위해 설정
      with:
        files: backend/build/test-results/**/*.xml
              
