name: CI

on:
  push:
    branches: [ "feature" ]
  pull_request:
    branches: [ "feature" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'

    - name: Grant Execute Permission For Gradlew
      run: chmod +x backend/gradlew

    - name: Cache Gradle packages
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build --info
        cache-dir: ~/.gradle/caches/
        project-dir: ./backend

    - name: Setup MySQL
      uses: samin/mysql-action@v1
      with:
        character set server: utf8
        mysql database: 'graphy'
        mysql user: 'graphy'
        mysql password: ${{ secrets.TEST_MYSQL_PASSWORD }}

    - name: Make properties
      run: |
        cd backend/src/main/resources
        touch ./application.properties
        echo "${{ secrets.TEST_PROPERTIES }}" > ./application.properties
      shell: bash

    - name: Test with Gradle # test application build
      run: |
        cd backend
        ./gradlew build --info

    - name: Test Results 
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: ${{ always() }} 
      with:
        files: backend/build/test-results/**/*.xml
