name: CI

on:
  push:
    branches: [ "feature" ]
  pull_request:
    branches: [ "feature" ]

jobs:
  backend-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
        

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: graphy/backend/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle-

    - name: Grant Execute Permission For Gradlew
      run: chmod +x backend/gradlew
      

    - name: Test with Gradle
      run: |
        cd backend
        ./gradlew build --info

    - name: Backend Test Results 
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: ${{ always() }} 
      with:
        files: backend/build/test-results/**/*.xml

  frontend-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [14, 16, 18] 
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Cache frontend packages
        uses: actions/cache@v2
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: ${{ runner.os }}-frontend-

      - run: cd frontend


      - run: npm ci

       
      - run: npm run format
        
      
      - run: npm run lint

      
      - run: npm test

      - name: Frontend Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: ${{ always() }} 
        with:
          files: frontend/test-results.xml