name: CI

on:
  push:
    branches: [ "feature" ]
  pull_request:
    branches: [ "feature" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
        
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
        
    - name: Build with Gradle
      run: |
        cd backend
        ./gradlew build -x test
    
    - name: Test with Gradle # test application build
      run: ./gradlew test

    - name: Test Results # test 후 result를 보기 위해 추가
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: ${{ always() }} # test가 실패해도 report를 남기기 위해 설정
      with:
        files: build/test-results/**/*.xml
              
